version: '3.8'
services:
  mysql:
    container_name: todo_api_db
    image: mysql:8.0.32
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1Qaz3Edc1006!!
      - MYSQL_ROOT_PASSWORD=1Qaz3Edc1006!!
      - MYSQL_DATABASE=todos
      - TZ=Asia/Seoul
    ports:
      - '3306'
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]
